Vagrant.configure("2") do |config|

  config.vm.define "kouferkaS" do |srv|
    srv.vm.box = "debian/bookworm64"
    srv.vm.hostname = "kouferkaS"
    srv.vm.provider "virtualbox" do |v|
      v.gui = false
      v.name = "kouferkaS"
      v.customize [
        'modifyvm', :id,
        '--natdnshostresolver1', 'on',
        '--memory', '2048',
        '--cpus', '2'
      ]
    end
    srv.vm.network :private_network, ip: "192.168.56.110"
    srv.vm.provision "shell", path: "srv.sh"
    srv.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
    srv.vm.network "forwarded_port", guest: 6443, host: 9090, protocol: "tcp"
  end
end