Vagrant.configure("2") do |config|

  config.vm.define "kouferkaS" do |srv|
          srv.vm.box = "ubuntu/trusty64"
          srv.vm.hostname = "kouferkaS"
          srv.vm.provider "virtualbox" do |v|
            v.memory = 512
            v.cpus = 1
            v.name = "kouferkaS"
          srv.vm.network :private_network, ip: "192.168.56.110"
          end
        end
      end